ymca-application/Controllers/Administration/AdministrationController.cs
using System.Web.Mvc;

namespace ymca_application.Controllers
{
    public class AdministrationController : Controller
    {
        // GET: /Administration/Index
        public ActionResult Index()
        {
            return View();
        }

        // GET: /Administration/Users
        public ActionResult Users()
        {
            return View();
        }

        // GET: /Administration/Programs
        public ActionResult Programs()
        {
            return View();
        }
    }
}

ymca-application/Controllers/Administration/UserController.cs
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using DataTables;

namespace ymca_application.Controllers
{
    public class APIUserController : ApiController
    {
        [System.Web.Http.Route("api/GetUsers")]
        [System.Web.Http.HttpGet]
        [System.Web.Http.HttpPost]
        public IHttpActionResult GetUsers()
        {
            var request = HttpContext.Current.Request;

            using (var db1 = new Database("sqlserver", ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                // Create a Datatables Editor object to gather users from database.
                var response = new Editor(db1, "AspNetUsers", "Id")
                    .Field(new Field("AspNetUsers.Id")
                    )
                    .Field(new Field("AspNetUsers.FirstName")
                    )
                    .Field(new Field("AspNetUsers.LastName")
                    )
                    .Field(new Field("AspNetUsers.Email")
                    )
                    .Field(new Field("AspNetUsers.PhoneNumber")
                    .SetFormatter(Format.IfEmpty(null))
                    .GetFormatter(Format.IfEmpty(null))
                    )
                    .Field(new Field("AspNetUsers.Address1")
                    .SetFormatter(Format.IfEmpty(null))
                    .GetFormatter(Format.IfEmpty(null))
                    )
                    .Field(new Field("AspNetUsers.Address2")
                    .SetFormatter(Format.IfEmpty(null))
                    .GetFormatter(Format.IfEmpty(null))
                    )
                    .Field(new Field("AspNetUsers.City")
                    .SetFormatter(Format.IfEmpty(null))
                    .GetFormatter(Format.IfEmpty(null))
                    )
                    .Field(new Field("AspNetUsers.State")
                    .SetFormatter(Format.IfEmpty(null))
                    .GetFormatter(Format.IfEmpty(null))
                    )
                    .Field(new Field("AspNetUsers.Zip")
                    .SetFormatter(Format.IfEmpty(null))
                    .GetFormatter(Format.IfEmpty(null))
                    )
                    .Field(new Field("AspNetUsers.Active")
                    )
                    .Field(new Field("AspNetUsers.LockoutEndDateUtc")
                    .SetFormatter(Format.IfEmpty(null))
                    .GetFormatter(Format.IfEmpty(null))
                    )
                    .Field(new Field("AspNetUsers.JoinDate")
                    )
                    .Field(new Field("AspNetUsers.Role")
                    .Options(new Options()
                    .Table("AspNetRoles")
                    .Value("Id")
                    .Label("Name"))
                    )
                    .Field(new Field("AspNetRoles.Id")
                    .Validator(Validation.NotEmpty())
                    )
                    .Field(new Field("AspNetRoles.Name")
                    .Validator(Validation.NotEmpty())
                    )
                    .LeftJoin("AspNetRoles", "AspNetUsers.Role", "=", "AspNetRoles.Id"
                    )
                    .Process(request)
                    .Data();

                // Return DataTables Editor user object.
                return Json(response);
            }
        }
    }

    public class MVCUserController : Controller
    {
        public void DisableUser(string UserId)
        {
            using (SqlConnection connection = new SqlConnection { ConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString })
            {
                // Open connection to database.
                connection.Open();

                // Execute stored procedure to disable a user.
                using (SqlCommand command = new SqlCommand("[Disable-User]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.Add("@UserId", SqlDbType.NVarChar).Value = UserId;

                    command.Prepare();
                    command.ExecuteNonQuery();
                }

                // Close connection.
                connection.Close();
            }
        }
    }
}

ymca-application/Views/Administration/Index.cshtml
@using ymca_application.Extensions

@{
    ViewBag.Title = "Administration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Administration</h2>

<hr />

@*Administration tasks*@
<div class="row" style="display:flex">
    @*Manage programs*@
    <div class="col-md-4" style="display: flex; flex-direction: column;">
        <h4>Manage Programs</h4>
        <p>Manage available programs — add, remove, update programs and view all program participants depending on role level.</p>
        <br />
        <p style="margin-top: auto;"><a class="btn btn-default" href='@Url.Action("Programs", "Administration")'>Click here &raquo;</a></p>
    </div>
    @*If user has a manager role or above, display manage users*@
    @{ if (User.Identity.GetRole() >= 4)
        {
            <div class="col-md-4" style="display: flex; flex-direction: column;">
                <h4>Manage Users</h4>
                <p>Manage user accounts — add, disable, update user accounts and view personal information such as email or access level.</p>
                <p style="margin-top: auto;"><a class="btn btn-default" href='@Url.Action("Users", "Administration")'>Click here &raquo;</a></p>
            </div>
        }
    }
    @*Display documentation staff according to user role level*@
    <div class="col-md-4" style="display: flex; flex-direction: column;">
        <h4>Documentation</h4>
        <p>View website functionality documentation.</p>
        @{ if (User.Identity.GetRole() == 5)
            {
                <p style="margin-top: auto;"><a class="btn btn-default" href='@Url.Content("~/Content/Documentation/IT_Manager_Manual.pdf")'>Click here &raquo;</a></p>
            }
            else if (User.Identity.GetRole() == 4)
            {
                <p style="margin-top: auto;"><a class="btn btn-default" href='@Url.Content("~/Content/Documentation/Administrator_Manual.pdf")'>Click here &raquo;</a></p>
            }
            else
            {
                <p style="margin-top: auto;"><a class="btn btn-default" href='@Url.Content("~/Content/Documentation/Staff_Manual.pdf")'>Click here &raquo;</a></p>
            }
        }
    </div>
</div>

ymca-application/Views/Administration/Users.cshtml
@using ymca_application.Extensions

@{
    ViewBag.Title = "Users";
    var Role = User.Identity.GetRole();
}

<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <title>Users</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/Editor-1.9.6/css/editor.dataTables.min.css" />
</head>
<body class="dataTables">
    <div class="container">
        <h1>Manage Users</h1>
        <br />
        @*Users DataTables table*@
        <table id="Users" class="display text-nowrap compact" style="width:100%">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Join Date</th>
                </tr>
            </thead>
        </table>
    </div>
</body>
</html>

@section scripts{
    <script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="~/Content/DataTables/Editor-1.9.6/js/dataTables.editor.min.js"></script>

    <script>

        var userForm, userTable, defaultUserFormLength = 25, defaultUserFormSort = 0;
        $(document).ready(function () {

            // Disable autocomplete on form fields
            $.extend(true, $.fn.dataTable.Editor.Field.defaults, {
                attr: {
                    autocomplete: 'off'
                }
            });

            // User Form
            userForm = new $.fn.dataTable.Editor({
                ajax: '/api/GetUsers',
                table: '#Users',
                fields: [
                    {
                        label: "First Name:",
                        name: "AspNetUsers.FirstName"
                    },
                    {
                        label: "Last Name:",
                        name: "AspNetUsers.LastName"
                    },
                    {
                        label: "Email:",
                        name: "AspNetUsers.Email"
                    },
                    {
                        label: "Phone Number:",
                        name: "AspNetUsers.PhoneNumber"
                    },
                    {
                        label: "Address:",
                        name: "AspNetUsers.Address1"
                    },
                    {
                        label: "Address 2:",
                        name: "AspNetUsers.Address2"
                   },
                    {
                        label: "City:",
                        name: "AspNetUsers.City"
                    },
                    {
                        label: "State:",
                        name: "AspNetUsers.State"
                    },
                    {
                        label: "Zip:",
                        name: "AspNetUsers.Zip"
                    },
                    {
                        label: "Date Joined:",
                        name: "AspNetUsers.JoinDate"
                    },
                    {
                        label: "Role:",
                        name: "AspNetUsers.Role",
                        type: "select",
                        placeholder: "Select a role"
                    },
                    {
                        label: "Active:",
                        name: "AspNetUsers.Active",
                        id: "activeUser",
                        type: "checkbox",
                        options: [
                            { label: "", "value": "True" }
                        ],
                        separator: "|",
                        unselectedValue: "False"
                    },
                    {
                        name: "AspNetUsers.LockoutEndDateUtc",
                        type: "hidden"
                    }
                ]
            });

            // Disable date field from being edited.
            userForm.field('AspNetUsers.JoinDate').disable();

            // On initCreate event.
            userForm.on('initCreate', function () {
                // Default active to true on create event.
                userForm.field('AspNetUsers.Active').val("True")
            });

            // On initSubmit event.
            userForm.on('initSubmit', function () {
                // If the Active is active on form submission set the date to null; else, set the date to the end of time.
                if (userForm.field('AspNetUsers.Active').val() === "True") {
                    userForm.field('AspNetUsers.LockoutEndDateUtc').set(null);
                } else {
                    userForm.field('AspNetUsers.LockoutEndDateUtc').set('9999-12-31');
                }
            });

            // User table
            userTable = $('#Users').DataTable({
                autoWidth: false,
                select: {
                    style: 'single'
                },
                // Default table lengths
                lengthMenu: [[defaultUserFormLength, 50, 100, -1], [defaultUserFormLength, 50, 100, "All"]],
                // Table data source
                ajax: {
                    url: '/api/GetUsers'
                },
                // Column defaults
                columnDefs: [
                    {
                        targets: 4,
                        visible: false
                    }
                ],
                // Table columns
                columns: [
                    { data: "AspNetUsers.FirstName" },
                    { data: "AspNetUsers.LastName" },
                    { data: "AspNetUsers.Email" },
                    { data: "AspNetUsers.JoinDate" },
                    { data: "AspNetUsers.Active" }
                ],
                rowCallback: function (row, data) {
                    if (data.AspNetUsers.Active === 'False') {
                        $(row).addClass('disabled-user');
                    } else {
                        $(row).removeClass('disabled-user');
                    }
                },
                // Control button layout
                dom: '<"floatRight"B><"clear">lfrtip',
                // Default table order
                order: [[0, "asc"]],
                buttons: [
                    { extend: "create", editor: userForm, formTitle: 'Create new user', attr: { id: 'newButton' } },
                    { extend: "edit", editor: userForm, formTitle: 'Edit existing user', attr: { id: 'editButton' } },
                    {
                        text: 'Enable', attr: { id: 'enableButton' }, action: function () {
                            // Get user row to be disabled.
                            var row = userTable.rows({ selected: true });

                            // Open remove API event on selected row.
                            userForm.edit(row, false).set('AspNetUsers.Active', 'True').submit();

                            // Switch enable/disable buttons
                            $('#enableButton').hide();
                            $('#disableButton').show();
                        }
                    },
                    {
                        text: 'Disable', attr: { id: 'disableButton' }, action: function () {
                            // Get user row to be disabled.
                            var row = userTable.rows({ selected: true });

                            // Open remove API event on selected row.
                            userForm.remove(
                                row,
                                {
                                    title: 'Disable user',
                                    message: '<p>Disabling this user will prevent the user from logging in and cancel their program registrations.</p><p>Are you sure you want to disable this user?</p>',
                                    buttons: [
                                        {
                                            text: 'Cancel', action: function () {
                                                // Close the remove form.
                                                this.close();
                                            }
                                        },
                                        {
                                            text: 'Disable', action: function () {
                                                // AJAX request to disable user.
                                                $.ajax({
                                                    url: '@Url.Action("DisableUser", "MVCUser")',
                                                    type: 'POST',
                                                    data: {
                                                        UserId: row.data()[0].AspNetUsers.Id
                                                    },
                                                    error: function (error) {
                                                        console.log(`Error ${error}`);
                                                    },
                                                    success: function () {
                                                        // Close the remove form.
                                                        userForm.close();

                                                        // Reload table data.
                                                        userTable.ajax.reload();
                                                    }
                                                });
                                            }
                                        }
                                    ]
                                }
                            );
                        }
                    },
                    {
                        // Show default view filter button
                        text: 'Show Default View', action: function (e, dt, node, config) {
                            userTable.search('')
                                .columns().search('')
                                .columns().order('')
                                .page.len(defaultUserFormLength)
                                .column(defaultUserFormSort).order('asc').draw();
                        }
                    }
                ]
            });

            // Hide buttons by default.
            $('#enableButton').hide();
            $('#disableButton').hide();

            // On select deselect event.
            userTable.on('select deselect', function () {
                var selectedRow = userTable.rows({ selected: true });
                if (selectedRow.count() === 0) {
                    $('#enableButton').hide();
                    $('#disableButton').hide();
                } else if (selectedRow.count() === 1 && selectedRow.data()[0].AspNetUsers.Active === 'True') {
                    $('#enableButton').hide();
                    $('#disableButton').show();
                    userTable.button(1).enable();
                } else {
                    $('#enableButton').show();
                    $('#disableButton').hide();
                    userTable.button(1).disable();
                }
            });
        });
    </script>
}